/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FeedbackType = IDL.Variant({
  'appreciate' : IDL.Null,
  'scold' : IDL.Null,
  'comment' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'studentClass' : IDL.Nat,
});
export const Time = IDL.Int;
export const StudentFeedback = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'feedbackType' : FeedbackType,
  'message' : IDL.Text,
  'student' : IDL.Principal,
  'parent' : IDL.Principal,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
  'senderRole' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const ParentProfilePublic = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'linkedStudentUsername' : IDL.Text,
});
export const PresenceInfo = IDL.Record({
  'isOnline' : IDL.Bool,
  'lastSeen' : Time,
});
export const StudentProfilePublic = IDL.Record({
  'username' : IDL.Text,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'studentClass' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudentFeedback' : IDL.Func(
      [IDL.Principal, IDL.Text, FeedbackType],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedbackById' : IDL.Func([IDL.Nat], [StudentFeedback], ['query']),
  'getFeedbackForStudent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudentFeedback)],
      ['query'],
    ),
  'getFeedbackFromParent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudentFeedback)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage), IDL.Bool],
      ['query'],
    ),
  'getParentByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ParentProfilePublic)],
      ['query'],
    ),
  'getParentProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ParentProfilePublic)],
      ['query'],
    ),
  'getPresence' : IDL.Func([IDL.Principal], [PresenceInfo], ['query']),
  'getStudentByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StudentProfilePublic)],
      ['query'],
    ),
  'getTypingStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getUserData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUserDataTypes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
  'registerParent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'setTyping' : IDL.Func([IDL.Bool], [], []),
  'updateFeedback' : IDL.Func([IDL.Nat, IDL.Text, FeedbackType], [], []),
  'updatePresence' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FeedbackType = IDL.Variant({
    'appreciate' : IDL.Null,
    'scold' : IDL.Null,
    'comment' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'studentClass' : IDL.Nat,
  });
  const Time = IDL.Int;
  const StudentFeedback = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'feedbackType' : FeedbackType,
    'message' : IDL.Text,
    'student' : IDL.Principal,
    'parent' : IDL.Principal,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
    'senderRole' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const ParentProfilePublic = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'linkedStudentUsername' : IDL.Text,
  });
  const PresenceInfo = IDL.Record({ 'isOnline' : IDL.Bool, 'lastSeen' : Time });
  const StudentProfilePublic = IDL.Record({
    'username' : IDL.Text,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'studentClass' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudentFeedback' : IDL.Func(
        [IDL.Principal, IDL.Text, FeedbackType],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFeedback' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedbackById' : IDL.Func([IDL.Nat], [StudentFeedback], ['query']),
    'getFeedbackForStudent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudentFeedback)],
        ['query'],
      ),
    'getFeedbackFromParent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudentFeedback)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage), IDL.Bool],
        ['query'],
      ),
    'getParentByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ParentProfilePublic)],
        ['query'],
      ),
    'getParentProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ParentProfilePublic)],
        ['query'],
      ),
    'getPresence' : IDL.Func([IDL.Principal], [PresenceInfo], ['query']),
    'getStudentByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StudentProfilePublic)],
        ['query'],
      ),
    'getTypingStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'getUserData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUserDataTypes' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'markMessagesRead' : IDL.Func([IDL.Principal], [], []),
    'registerParent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserData' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'setTyping' : IDL.Func([IDL.Bool], [], []),
    'updateFeedback' : IDL.Func([IDL.Nat, IDL.Text, FeedbackType], [], []),
    'updatePresence' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };