/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'isRead' : boolean,
  'timestamp' : Time,
  'senderRole' : string,
  'senderId' : Principal,
}
export type FeedbackType = { 'appreciate' : null } |
  { 'scold' : null } |
  { 'comment' : null };
export interface ParentProfile {
  'username' : string,
  'password' : Password,
  'name' : string,
  'linkedStudentUsername' : string,
}
export interface Password { 'hash' : string }
export interface PresenceInfo { 'isOnline' : boolean, 'lastSeen' : Time }
export interface StudentFeedback {
  'id' : bigint,
  'createdAt' : Time,
  'feedbackType' : FeedbackType,
  'message' : string,
  'student' : Principal,
  'parent' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'school' : string,
  'name' : string,
  'studentClass' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudentFeedback' : ActorMethod<[Principal, string, FeedbackType], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFeedback' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedbackById' : ActorMethod<[bigint], StudentFeedback>,
  'getFeedbackForStudent' : ActorMethod<[Principal], Array<StudentFeedback>>,
  'getFeedbackFromParent' : ActorMethod<[Principal], Array<StudentFeedback>>,
  'getMessages' : ActorMethod<[Principal], [Array<ChatMessage>, boolean]>,
  'getParentByUsername' : ActorMethod<[string], [] | [ParentProfile]>,
  'getPresence' : ActorMethod<[Principal], PresenceInfo>,
  'getTypingStatus' : ActorMethod<[Principal], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessagesRead' : ActorMethod<[Principal], undefined>,
  'registerParent' : ActorMethod<[string, string, string, string], undefined>,
  'registerStudent' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string, string], undefined>,
  'setTyping' : ActorMethod<[boolean], undefined>,
  'updateFeedback' : ActorMethod<[bigint, string, FeedbackType], undefined>,
  'updatePresence' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];