/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'weightage' : bigint,
  'name' : string,
  'completed' : boolean,
  'subjectId' : bigint,
}
export interface Flashcard {
  'id' : bigint,
  'front' : string,
  'learned' : boolean,
  'back' : string,
  'chapterId' : bigint,
  'subjectId' : bigint,
}
export interface MCQAnswer { 'questionId' : bigint, 'selectedOption' : bigint }
export interface MCQQuestion {
  'id' : bigint,
  'correctOption' : bigint,
  'questionText' : string,
  'options' : Array<string>,
}
export interface MockTest {
  'id' : bigint,
  'name' : string,
  'subjectId' : bigint,
  'questions' : Array<MCQQuestion>,
}
export interface Note {
  'id' : bigint,
  'content' : string,
  'imageData' : [] | [string],
  'createdAt' : Time,
  'chapterId' : bigint,
}
export interface PersonalBest {
  'totalQuestionsPracticed' : bigint,
  'fastestTestTime' : bigint,
  'rankLabel' : string,
  'highestScorePerSubject' : Array<[bigint, bigint]>,
  'totalChaptersCompleted' : bigint,
  'longestStreak' : bigint,
}
export interface PlannerTask {
  'id' : bigint,
  'startTime' : string,
  'title' : string,
  'date' : Time,
  'completed' : boolean,
  'description' : string,
}
export interface ProgressSummary {
  'totalTasks' : bigint,
  'totalTargets' : bigint,
  'totalMockTestsAttempted' : bigint,
  'totalTargetsAchieved' : bigint,
  'mockTestAverageScore' : bigint,
  'totalTasksCompleted' : bigint,
  'subjectProgress' : Array<SubjectProgress>,
}
export interface Question {
  'id' : bigint,
  'chapterId' : bigint,
  'answer' : string,
  'questionText' : string,
  'subjectId' : bigint,
}
export interface QuestionResult {
  'correctOption' : bigint,
  'isCorrect' : boolean,
  'questionText' : string,
  'questionId' : bigint,
  'selectedOption' : bigint,
}
export interface Reminder {
  'id' : bigint,
  'text' : string,
  'targetId' : [] | [bigint],
  'dateTime' : Time,
}
export interface RevisionTask {
  'id' : bigint,
  'plannerTaskId' : [] | [bigint],
  'completed' : boolean,
  'dueDate' : Time,
  'chapterId' : bigint,
  'subjectId' : bigint,
  'revisionNumber' : bigint,
}
export interface StudyStreak {
  'lastActiveDate' : Time,
  'topStreak' : bigint,
  'currentStreak' : bigint,
}
export interface Subject { 'id' : bigint, 'name' : string }
export interface SubjectProgress {
  'completedChapters' : bigint,
  'subjectName' : string,
  'subjectId' : bigint,
  'totalChapters' : bigint,
}
export interface Target {
  'id' : bigint,
  'title' : string,
  'completed' : boolean,
  'description' : string,
  'deadline' : Time,
}
export interface TestAttempt {
  'id' : bigint,
  'report' : TestReport,
  'attemptedAt' : Time,
  'testId' : bigint,
}
export interface TestReport {
  'total' : bigint,
  'testName' : string,
  'results' : Array<QuestionResult>,
  'score' : bigint,
  'timeTaken' : bigint,
  'testId' : bigint,
  'percentage' : bigint,
}
export type Time = bigint;
export interface UserAchievement {
  'id' : bigint,
  'achievedAt' : Time,
  'achievementType' : string,
}
export interface UserProfile {
  'username' : string,
  'school' : string,
  'name' : string,
  'studentClass' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / addChapter: only authenticated users (#user) can add chapters.
   */
  'addChapter' : ActorMethod<[bigint, string, bigint], bigint>,
  /**
   * / addFlashcard: only authenticated users (#user) can add flashcards.
   */
  'addFlashcard' : ActorMethod<[bigint, bigint, string, string], bigint>,
  /**
   * / addNote: only authenticated users (#user) can add notes.
   */
  'addNote' : ActorMethod<[bigint, string, [] | [string]], bigint>,
  /**
   * / addPlannerTask: only authenticated users (#user) can add planner tasks.
   */
  'addPlannerTask' : ActorMethod<[string, string, Time, string], bigint>,
  /**
   * / addQuestion: only authenticated users (#user) can add questions.
   */
  'addQuestion' : ActorMethod<[bigint, bigint, string, string], bigint>,
  /**
   * / addReminder: only authenticated users (#user) can add reminders.
   */
  'addReminder' : ActorMethod<[string, Time, [] | [bigint]], bigint>,
  'addSubject' : ActorMethod<[string], bigint>,
  /**
   * / addTarget: only authenticated users (#user) can add targets.
   */
  'addTarget' : ActorMethod<[string, string, Time], bigint>,
  /**
   * / adminListUsers: only admins can list all users.
   */
  'adminListUsers' : ActorMethod<[], Array<Principal>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / completePlannerTask: only authenticated users (#user) can update their own planner tasks.
   * / Completing a task also updates the study streak.
   */
  'completePlannerTask' : ActorMethod<[bigint, boolean], undefined>,
  /**
   * / completeTarget: only authenticated users (#user) can update their own targets.
   */
  'completeTarget' : ActorMethod<[bigint, boolean], undefined>,
  /**
   * / createMockTest: only authenticated users (#user) can create mock tests.
   */
  'createMockTest' : ActorMethod<[string, bigint, Array<MCQQuestion>], bigint>,
  /**
   * / deleteFlashcard: only authenticated users (#user) can delete their own flashcards.
   */
  'deleteFlashcard' : ActorMethod<[bigint], undefined>,
  /**
   * / deleteMockTest: only authenticated users (#user) can delete their own mock tests.
   */
  'deleteMockTest' : ActorMethod<[bigint], undefined>,
  /**
   * / deleteNote: only authenticated users (#user) can delete their own notes.
   */
  'deleteNote' : ActorMethod<[bigint], undefined>,
  /**
   * / deletePlannerTask: only authenticated users (#user) can delete their own planner tasks.
   */
  'deletePlannerTask' : ActorMethod<[bigint], undefined>,
  /**
   * / deleteQuestion: only authenticated users (#user) can delete their own questions.
   */
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  /**
   * / deleteReminder: only authenticated users (#user) can delete their own reminders.
   */
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  /**
   * / deleteTarget: only authenticated users (#user) can delete their own targets.
   */
  'deleteTarget' : ActorMethod<[bigint], undefined>,
  /**
   * / getAchievements: only authenticated users (#user) can view their achievements.
   */
  'getAchievements' : ActorMethod<[], Array<UserAchievement>>,
  /**
   * / getAllFlashcards: only authenticated users (#user) can view all their flashcards.
   */
  'getAllFlashcards' : ActorMethod<[], Array<Flashcard>>,
  /**
   * / getAllPlannerTasks: only authenticated users (#user) can view all their planner tasks.
   */
  'getAllPlannerTasks' : ActorMethod<[], Array<PlannerTask>>,
  /**
   * / getCallerUserProfile: only authenticated users (#user) can call this.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / getChaptersForSubject: only authenticated users (#user) can view their chapters.
   */
  'getChaptersForSubject' : ActorMethod<[bigint], Array<Chapter>>,
  /**
   * / getFlashcardsForChapter: only authenticated users (#user) can view their flashcards.
   */
  'getFlashcardsForChapter' : ActorMethod<[bigint], Array<Flashcard>>,
  /**
   * / getMockTest: only authenticated users (#user) can view a specific mock test.
   */
  'getMockTest' : ActorMethod<[bigint], [] | [MockTest]>,
  /**
   * / getMockTests: only authenticated users (#user) can view their mock tests.
   */
  'getMockTests' : ActorMethod<[], Array<MockTest>>,
  /**
   * / getNotesForChapter: only authenticated users (#user) can view their notes.
   */
  'getNotesForChapter' : ActorMethod<[bigint], Array<Note>>,
  /**
   * / getPendingRevisionTasks: only authenticated users (#user) can view their pending revision tasks.
   */
  'getPendingRevisionTasks' : ActorMethod<[], Array<RevisionTask>>,
  /**
   * / getPersonalBest: only authenticated users (#user) can view their personal best stats.
   */
  'getPersonalBest' : ActorMethod<[], PersonalBest>,
  /**
   * / getPlannerTasksForDate: only authenticated users (#user) can view their planner tasks.
   */
  'getPlannerTasksForDate' : ActorMethod<[Time], Array<PlannerTask>>,
  /**
   * / getPlannerTasksForMonth: only authenticated users (#user) can view their planner tasks.
   */
  'getPlannerTasksForMonth' : ActorMethod<[bigint, bigint], Array<PlannerTask>>,
  /**
   * / getProgressSummary: only authenticated users (#user) can view their progress.
   */
  'getProgressSummary' : ActorMethod<[], ProgressSummary>,
  /**
   * / getQuestionBank: only authenticated users (#user) can view the question bank.
   */
  'getQuestionBank' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<Question>
  >,
  /**
   * / getQuestionsForChapter: only authenticated users (#user) can view their questions.
   */
  'getQuestionsForChapter' : ActorMethod<[bigint], Array<Question>>,
  /**
   * / getReminders: only authenticated users (#user) can view their reminders.
   */
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  /**
   * / getRevisionTasks: only authenticated users (#user) can view their revision tasks.
   */
  'getRevisionTasks' : ActorMethod<[], Array<RevisionTask>>,
  /**
   * / getStudyStreak: only authenticated users (#user) can view their study streak.
   */
  'getStudyStreak' : ActorMethod<[], StudyStreak>,
  /**
   * / getSubjects: only authenticated users (#user) can view their subjects.
   */
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  /**
   * / getTargets: only authenticated users (#user) can view their targets.
   */
  'getTargets' : ActorMethod<[], Array<Target>>,
  /**
   * / getTestAttempts: only authenticated users (#user) can view their test attempts.
   */
  'getTestAttempts' : ActorMethod<[], Array<TestAttempt>>,
  /**
   * / getTestAttemptsForTest: only authenticated users (#user) can view test attempts for a specific test.
   */
  'getTestAttemptsForTest' : ActorMethod<[bigint], Array<TestAttempt>>,
  /**
   * / getUserProfile: users can only view their own profile; admins can view any.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / markChapterCompleted: only authenticated users (#user) can update their chapters.
   * / When a chapter is marked complete, revision tasks are automatically scheduled.
   */
  'markChapterCompleted' : ActorMethod<[bigint, boolean], undefined>,
  /**
   * / markFlashcardLearned: only authenticated users (#user) can update their own flashcards.
   */
  'markFlashcardLearned' : ActorMethod<[bigint, boolean], undefined>,
  /**
   * / markRevisionTaskCompleted: only authenticated users (#user) can update their own revision tasks.
   */
  'markRevisionTaskCompleted' : ActorMethod<[bigint, boolean], undefined>,
  /**
   * / recordDailyLogin: only authenticated users (#user) can record their daily login for streak tracking.
   */
  'recordDailyLogin' : ActorMethod<[], StudyStreak>,
  /**
   * / Register is open to anyone (guests), since users need to register before having a #user role.
   */
  'register' : ActorMethod<[string, string, string, bigint], undefined>,
  /**
   * / saveCallerUserProfile: only authenticated users (#user) can save their own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / submitMockTest: only authenticated users (#user) can submit mock tests.
   */
  'submitMockTest' : ActorMethod<
    [bigint, Array<MCQAnswer>, bigint],
    TestReport
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];